# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipg3iLBJeLiLs6Hg7MIdulVYVD5S8c7l
"""

import torch
import torch.nn as nn
import torch.optim as optim
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

def market(start_date="2020-01-01", end_date="2026-01-01"):
    tickers = ["SHEL", "BP", "^TNX", "^VIX"]
    data = yf.download(tickers, start=start_date, end=end_date)['Close']

    data = data.ffill().dropna()

    df = pd.DataFrame(index=data.index)

    ratio = data['SHEL'].iloc[0] / data['BP'].iloc[0]
    df['Spread'] = data['SHEL'] - (data['BP'] * ratio)

    df['Spread_ZScore'] = (df['Spread'] - df['Spread'].rolling(20).mean()) / df['Spread'].rolling(20).std()

    df['Treasury_Yield'] = data['^TNX']

    df['VIX'] = data['^VIX']

    df = df.dropna()

    future_spread = df['Spread'].shift(-5)
    df['Target'] = (future_spread > df['Spread']).astype(int)
    df = df.iloc[:-5]

    return df

def create(df, sequence=15):
    scaler = StandardScaler()
    feature_cols = ['Spread_ZScore', 'Treasury_Yield', 'VIX']
    scaled_features = scaler.fit_transform(df[feature_cols])
    targets = df['Target'].values

    X, y = [], []
    for i in range(len(scaled_features) - sequence):
        X.append(scaled_features[i : i + sequence])
        y.append(targets[i + sequence])

    return torch.tensor(np.array(X), dtype=torch.float32), torch.tensor(np.array(y), dtype=torch.float32).unsqueeze(1)

class Alpha(nn.Module):
    def __init__(self, input, hidden=16, layers=1, dropout=0.4):
        super(Alpha, self).__init__()
        self.lstm = nn.LSTM(input, hidden, layers, batch_first=True)
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        lstm_out, _ = self.lstm(x)
        last_step = self.dropout(lstm_out[:, -1, :])
        return self.sigmoid(self.fc(last_step))

if __name__ == "__main__":
    df = market()
    print(f"Total trading days: {len(df)}")

    X, y = create(df, sequence=15)

    split = int(len(X) * 0.8)
    X_train, X_val = X[:split], X[split:]
    y_train, y_val = y[:split], y[split:]

    model = Alpha(input=3, hidden=32, layers=1, dropout=0.2)
    criterion = nn.BCELoss()

    optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)
    epochs = 50
    train_loss, val_loss = [], []

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()

        predictions = model(X_train)
        loss = criterion(predictions, y_train)
        loss.backward()
        optimizer.step()

        model.eval()
        with torch.no_grad():
            preds = model(X_val)
            val = criterion(preds, y_val)

            val_class = (preds > 0.5).float()
            accuracy = (val_class == y_val).float().mean()

        train_loss.append(loss.item())
        val_loss.append(val.item())

        if (epoch + 1) % 10 == 0:
            print(f"Epoch [{epoch+1:02d}/{epochs}] | Train Loss: {loss.item():.4f} | Val Loss: {val.item():.4f} | Val Accuracy: {accuracy.item()*100:.1f}%") # Corrected: Changed val_loss.item() to val.item() for current epoch's validation loss.

    plt.figure(figsize=(10, 5))
    plt.plot(train_loss, label="Regularized Train Loss")
    plt.plot(val_loss, label="Regularized Validation Loss")
    plt.title("LSTM Convergence Profile Under High Regularization")
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()