# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15y05xQQnfuhXfFkeJA6ncTkYHJwcoXJ5
"""

import numpy as np
import pandas as pd
import yfinance as yf
from hmmlearn import hmm
import matplotlib.pyplot as plt

def pairs(ticker1="SHEL", ticker2="BP", start_date="2021-01-01", end_date="2026-01-01"):
    data = yf.download([ticker1, ticker2], start=start_date, end=end_date)['Close']

    data['spread'] = data[ticker1] - (data[ticker2] * (data[ticker1].iloc[0] / data[ticker2].iloc[0]))

    data['returns'] = np.log(data['spread'] / data['spread'].shift(1))
    data['vol'] = data['returns'].rolling(window=10).std()

    return data.dropna()

def hmm_model(df):
    X = df[['returns', 'vol']].values

    model = hmm.GaussianHMM(n_components=2, covariance_type="diag", n_iter=1000, random_state=42)
    model.fit(X)

    hidden = model.predict(X)

    posterior = model.predict_proba(X)

    df['Hidden'] = hidden
    df['State_0'] = posterior[:, 0]
    df['State_1'] = posterior[:, 1]

    return model, df

def analyze(model, df, ticker1, ticker2):

    state_0 = float(model.covars_[0, 1, 1])
    state_1 = float(model.covars_[1, 1, 1])

    high_vol = 1 if state_1 > state_0 else 0
    low_vol = 0 if high_vol == 1 else 1

    print("\nHMM Model Parameters")
    print(f"Transition Matrix:\n{model.transmat_}")
    print(f"State {low_vol} is the Low Volatility Regime.")
    print(f"State {high_vol} is the High Volatility Regime.")

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

    ax1.plot(df.index, df['spread'], color='black', lw=1.5, label='SHEL-BP Spread')
    ax1.set_title("Asset Spread & Inferred Volatility Regimes", fontsize=14)
    ax1.set_ylabel("Spread Price")

    vol_mask = df['Hidden'] == high_vol
    ax1.fill_between(df.index, df['spread'].min(), df['spread'].max(), where=vol_mask, color='red', alpha=0.2, label='High Vol Regime')
    ax1.legend(loc='upper left')

    high_prob = f'State_{high_vol}'
    ax2.plot(df.index, df[high_prob], color='red', lw=1, label='P(High Volatility)')
    ax2.axhline(0.5, linestyle='--', color='gray', alpha=0.5)
    ax2.set_title("Posterior Probability of High Volatility Regime", fontsize=12)
    ax2.set_ylabel("Probability")
    ax2.set_xlabel("Date")
    ax2.legend(loc='upper left')

    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    t1, t2 = "SHEL", "BP"
    df = pairs(ticker1=t1, ticker2=t2)
    model, df_states = hmm_model(df)
    analyze(model, df_states, t1, t2)